package leetCode;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;

import org.junit.Test;

public class TwoSumTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(TwoSum.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		TwoSum target = new TwoSum();
		assertThat(target, notNullValue());
	}

	@Test
	public void twoSum_A$intArray$int() throws Exception {
		// TODO auto-generated by JUnit Helper.
		TwoSum target = new TwoSum();
		int[] nums = new int[] {};
		int target_ = 0;
		int[] actual = target.twoSum(nums, target_);
		int[] expected = null;
		assertThat(actual, is(equalTo(expected)));
	}

}
