package leetCode;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;

import org.junit.Test;

public class ZigZagTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(ZigZag.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		ZigZag target = new ZigZag();
		assertThat(target, notNullValue());
	}

	@Test
	public void convert_A$String$int() throws Exception {
		// TODO auto-generated by JUnit Helper.
		ZigZag target = new ZigZag();
		String s = null;
		int numRows = 0;
		String actual = target.convert(s, numRows);
		String expected = null;
		assertThat(actual, is(equalTo(expected)));
	}

}
